import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center p-6 md:p-10 pb-12">
          <div className="flex flex-col max-w-5xl w-full items-center gap-24">
              <div className="flex flex-col max-w-3xl w-full">
                {children}
              </div>
          </div>
        </main>
      </body>
    </html>
  );
}
